services:
  laravel:
    build:
        contex: ./docker/app
        dockerfile: Dockerfile
    image: devopsas3/app:latest 
    networks:
        - sysops

    volumes:
       - ./laravel/:/var/www/html
    ports:
       - 8080:80
    working_dir: /var/www/
  redis:
    image: redis:alpine
    networks:
      - sysops
    volumes:
      - redisdata:/data
  mysqldb:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: dadt01group151234
      MYSQL_DATABASE: laravel
      MYSQL_USER: laraveluser
      MYSQL_PASSWORD: dadt01group151234
    ports:
      - 33060:3306
    networks:
      - sysops
    volumes:
      - mysqldbdata:/var/lib/mysql
networks:
  sysops:
    driver: bridge
volumes:
  mysqldbdata:
    driver: local
  redisdata:
    driver: local
