version: '3.8'

services:
  dadt01group15app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: dadt01group15app
    ports:
      - "8080:80"
    volumes:
      - ./laravel:/var/www/html
    networks:
      - sysops
    depends_on:
      - mysqldbcontainer
      - rediscontainer

  mysqldbcontainer:
    image: mysql:8.0
    container_name: mysqldbcontainer
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: laraveldb
      MYSQL_USER: laraveluser
      MYSQL_PASSWORD: laravelpass
    volumes:
      - mysqldbdatavolume:/var/lib/mysql
    networks:
      - sysops

  rediscontainer:
    image: redis:alpine
    container_name: rediscontainer
    volumes:
      - redisdatavolume:/data
    networks:
      - sysops

networks:
  sysops:

volumes:
  mysqldbdatavolume:
  redisdatavolume:
